Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"  # Cambiar a focal64 para Ubuntu 20.04 LTS, pero este archivo será sobreescrito por el ISO
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Ubuntu-24.04"  # Nombre de la VM en VirtualBox
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end

